Updated to new quilt commands and changed CPU throttling
mchang6137/throttlebot pull request #1
Opened 2017-04-20 06:01 UTC by atalreja

2017-04-20 19:41 UTC, mchang6137 commented on src/measure_performance_MEAN_py3.py
> +	client.connect(ip, username="quilt", password="SSH_PASSWORD")
Why do you need SSH_PASSWORD? It should only require your private key to connect to the remote server right?

2017-04-20 19:45 UTC, mchang6137 commented on src/modify_resources.py
> +    # cpu_quota = int(cpu_quota * get_num_cores(ssh_client) * 1000000)
Remove comments.

2017-04-20 19:46 UTC, mchang6137 commented on src/modify_resources.py
> +            print update_command
Remove this print.

2017-04-20 19:56 UTC, mchang6137 requested changes
You need some considerations about the number of cores on the machines. Look into this on the Redhat documentation. It looks like there is also some assumption about containers being on certain cores? This assumption will need to be removed. Otherwise, looks good.

2017-04-20 19:56 UTC, mchang6137 commented on src/modify_resources.py
> +            core += 1
Is the assumption that each container is only pinned to a single core? Also, you should not assume that container_name[0] is assigned to the 0th core, container_name[1] is assigned to the 1st core, etc. Why update the cpuset anyways?

2017-04-20 19:56 UTC, mchang6137 commented on src/modify_resources.py
> +    cpu_quota = int((float(cpu_quota) / 10) * 1000000)
Isn't there some assumption about the CPU quota being some multiple of the number of cores in the machine?

2017-04-24 10:08 UTC, atalreja commented
Fixed changes that you commented on and verified that it works without making the assumption of pinning to a core and using cpuset. The skeleton code that you had for cpu quota turned out to be the correct way to do it.

2017-04-24 20:41 UTC, merged