Baseline sanity check
mchang6137/throttlebot pull request #25
Opened 2017-11-23 06:09 UTC by hantaowang

Reruns the baseline after every iteration. If current test of baseline deviates from the original baseline by more than 10% (can be changed), it exits.

2017-11-25 21:17 UTC, mchang6137 commented on src/modify_resources.py
> +container_blacklist = ['ovn-controller', 'minion', 'ovs-vswitchd', 'ovsdb-server', 'etcd', 'hantaowang/lumbersexual']
Note that we need to organize the blacklist in a centralized manner.

2017-11-25 21:22 UTC, mchang6137 requested changes

2017-11-25 21:22 UTC, mchang6137 commented on src/test_config.cfg
> -baseline_trials = 5
Can you add test_config.cfg to the .gitignore?

2017-11-25 21:22 UTC, mchang6137 commented on src/run_throttlebot.py
> +    sys_config['rerun_baseline'] = config.getboolean('Basic', 'rerun_baseline')
Add documentation in README about what this parameter means.

2017-11-25 21:22 UTC, mchang6137 commented on src/modify_resources.py
> +container_blacklist = ['ovn-controller', 'minion', 'ovs-vswitchd', 'ovsdb-server', 'etcd', 'hantaowang/lumbersexual']
Should maintain separate blacklists: one for the Quilt blacklist and one for application specific services .

2017-11-25 21:57 UTC, hantaowang commented
not sure how to remove test_config.cfg from merge but I have added it to the gitignore

2017-11-27 20:23 UTC, mchang6137 approved these changes

2017-11-27 20:24 UTC, merged